---
# tasks file for helloworld

- name: Copying the application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld

- name: Check list of running Node.js apps
  command: forever list
  register: forever_list
  changed_when: false

- name: Start Node.js app HelloWorld with forever
  command: forever start /home/ec2-user/helloworld.js
  when: forever_list.stdout.find('/home/ec2-user/helloworld.js') == -1
